#!/bin/bash

# Set the hostname
sudo hostnamectl set-hostname hunkon-os

# Update /etc/hosts
sudo sed -i 's/^127.0.1.1.*/127.0.1.1    hunkon-os/' /etc/hosts

# Reboot to apply changes
echo "Hostname changed to hunkon-os. Rebooting..."
sudo reboot
